spring:
    application:
        name: chat-app-with-kafka

    datasource:
        url: jdbc:postgresql://localhost:5432/chat_app
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10  # Adjust based on your application's needs
            minimum-idle: 5
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update  # Options: none, validate, update, create, create-drop
        show-sql: true