spring:
    application:
        name: chat-app-with-kafka

    datasource:
        url: jdbc:h2:mem:h2
        driver-class-name: org.h2.Driver
        username: sa
        password:
        hikari:
            maximum-pool-size: 10
    h2:
        console:
            enabled: true
            path: /h2-console


